### ISSUE TITLE
[Question]Register action in unordered way

### ISSUE THREAD

**Issue by eduardhasanaj** [tansey/holdem_engine#2]
Hi!
I wanted to register an action in an unordered way. We have player A B C.
Its turn of player B, but while we wait for player B, player c disconnects. Can I add a fold action for c without breaking the game?

Best wishes

**Comment by tansey** [comment]
Seems like you need to implement a new IPlayer type that checks if the player has disconnected and folds for them.

**Comment by eduardhasanaj** [comment]
I have modified a bit your code and Introduced an interface ISeatData which gives me playername, state of seat etc. Thank you for your help
